list: 
  handler: services/account/listAccount.handler
  events:
    - http:
        path: account/list
        method: GET

create:
    handler: services/account/createAccount.handler
    events:
      - http: 
          path: account/create
          method: POST