org: kyukyu
app: exp-tracker
service: exp-tracker
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs16.x

functions:
    - ${file(services/account/serverless.yml)}
    - ${file(services/transaction/serverless.yml)}
    - ${file(services/user/serverless.yml)}


package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
