org: kyukyu
app: my-serverless
service: my-serverless
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs16.x

functions:
    - ${file(services/user/serverless.yml)}

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
