accountList: 
  handler: services/account/listAccount.handler
  events:
    - http:
        path: account/list
        method: GET

createAccount:
    handler: services/account/createAccount.handler
    events:
      - http: 
          path: account/create
          method: POST

transactionList:
    handler: services/transaction/listTransaction.handler
    events:
      - http: 
          path: transaction/list
          method: GET

createTransaction:
    handler: services/transaction/createTransaction.handler
    events:
      - http: 
          path: transaction/create
          method: POST

userCreate:
  handler: services/user/createUser.handler
  events:
    - http: 
        path: user/create
        method: POST

categoryList:
  handler: services/category/listCategory.handler
  events:
    - http: 
        path: category/list
        method: GET

categoryCreate:
  handler: services/category/createCategory.handler
  events:
    - http: 
        path: category/create
        method: POST

listTopCategories:
  handler: services/analytic/listTopCategories.handler
  events:
    - http: 
        path: analytic/top-categories
        method: GET

claculateTotalBalance:
  handler: services/analytic/claculateTotalBalance.handler
  events:
    - http: 
        path: analytic/total-balance
        method: GET

claculateTotalExpense:
  handler: services/analytic/claculateTotalExpense.handler
  events:
    - http: 
        path: analytic/total-expense
        method: GET