list:
  handler: services/transaction/listTransaction.handler
  events:
    - http: 
        path: transaction/list
        method: GET

create:
    handler: services/transaction/createTransaction.handler
    events:
      - http: 
          path: transaction/create
          method: POST